# Generated by Django 5.1a1 on 2024-07-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
